### ISSUE TITLE
Planned address for new CSRs

### ISSUE THREAD

**Issue by chuanhua** [sifive/clic-spec#28]
What are the planned addresses for the new CSRs proposed in the CLIC spec?
For M-mode CSRs:
- mtvt

- mnxti

- mintstatus

- mscratchcsw

- mscratchcswl

For S-mode CSRs:
- stvt

- snxti

- sintstatus

- sscratchcsw

- sscratchcswl

**Comment by jim-wilson** [comment]
You can find the addresses at the top of section 3 "CLIC CSRs".

**Comment by chuanhua** [comment]
This is great. I missed that. Thanks.
