### ISSUE TITLE
Be sure reads have no side effects

### ISSUE THREAD

**Issue by ilg-ul** [sifive/clic-spec#9]
While working on the Peripheral Viewer for the SiFive devices I remember there were some registers which had side effects when reading. Please note that modern debuggers are able to monitor a memory area and display the content each time the execution halts, which obviously implies a sequence of read accesses; if those reads have side effects, the results are most of the time unwanted/unexpected.

I think that such designs should be generally avoided.

This is only a reminder, to check the CLIC design, if reading any of the memory mapped registers has any side effects, in order to avoid such behaviour.

**Comment by kasanovic** [comment]
The current CLIC spec does not have any side effects on memory-mapped register reads.
